//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessRoleView
    {
        public int AccessNameID { get; set; }
        public string AccessName { get; set; }
        public int AccessGroupId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> RoleId { get; set; }
    }
}
