//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessName
    {
        public int AccessNameID { get; set; }
        public int AccessGroupId { get; set; }
        public string AccessName1 { get; set; }
        public string updatedBy { get; set; }
        public System.DateTime updatedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedRemarks { get; set; }
        public bool DeleteFlag { get; set; }
        public bool AccessNameStatus { get; set; }
    
        public virtual AccessGroupMaster AccessGroupMaster { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        public virtual UserDetail UserDetail1 { get; set; }
    }
}
