//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorizationItem
    {
        public int RoleAccessNameid { get; set; }
        public int RoleId { get; set; }
        public int AccessNamesId { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime Updateddate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> Deleteddate { get; set; }
        public string DeletedRemarks { get; set; }
        public bool DeleteFlag { get; set; }
        public Nullable<bool> AccessNameStatus { get; set; }
    }
}
