//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditApprover
    {
        public string EmployeeNo { get; set; }
        public string Name { get; set; }
        public string role { get; set; }
        public Nullable<byte> roleorder { get; set; }
        public byte DepartmentId { get; set; }
        public decimal minpAVAlue { get; set; }
        public string AuthorizationType { get; set; }
        public decimal MaxPAValue { get; set; }
        public byte MaxDays { get; set; }
        public byte MinDays { get; set; }
        public string FunctionalRoleId { get; set; }
    }
}
