//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayRfqTermsByRevisionId
    {
        public int RfqTermsid { get; set; }
        public string Terms { get; set; }
        public int TermId { get; set; }
        public string Remarks { get; set; }
        public int RFQrevisionId { get; set; }
        public string RFQNo { get; set; }
        public string VendorResponse { get; set; }
    }
}
