//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeemappingtopurchase
    {
        public int Authid { get; set; }
        public string FunctionalRoleId { get; set; }
        public string Employeeid { get; set; }
        public int PAmapid { get; set; }
        public string Department { get; set; }
        public bool LessBudget { get; set; }
        public bool MoreBudget { get; set; }
        public string Name { get; set; }
        public decimal MaxPAValue { get; set; }
        public int DeptId { get; set; }
        public bool DeleteFlag { get; set; }
        public decimal MinPAValue { get; set; }
        public string AuthorizationType { get; set; }
    }
}
