//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employeemappingtocredit
    {
        public int Authid { get; set; }
        public decimal MinPAValue { get; set; }
        public decimal MaxPAValue { get; set; }
        public int DeptId { get; set; }
        public string EmployeeNo { get; set; }
        public string Name { get; set; }
        public string AuthorizationType { get; set; }
        public byte CreditdaysId { get; set; }
        public byte MinDays { get; set; }
        public byte MaxDays { get; set; }
        public int CRApprovalId { get; set; }
    }
}
