//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetMprPaDetailsByFilter
    {
        public Nullable<byte> DepartmentID { get; set; }
        public string DocumentNo { get; set; }
        public string Department { get; set; }
        public Nullable<byte> BuyerGroupId { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string BuyerGroup { get; set; }
        public string PONO { get; set; }
        public string POItemNo { get; set; }
        public int PAId { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
    }
}
