//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GetmprApproverdeatil
    {
        public string RoleName { get; set; }
        public string Approver { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public Nullable<byte> XOrder { get; set; }
        public string Department { get; set; }
        public string ApproversRemarks { get; set; }
        public string ApprovalStatus { get; set; }
        public string RequestedBy { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
        public Nullable<byte> DepartmentID { get; set; }
        public Nullable<byte> BuyerGroupId { get; set; }
        public int PAId { get; set; }
    }
}
