//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalGroupEmployee
    {
        public int grpempid { get; set; }
        public Nullable<short> GlobalGroupId { get; set; }
        public string EmployeeNo { get; set; }
        public Nullable<System.DateTime> updatedon { get; set; }
        public string updatedby { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual GlobalGroup GlobalGroup { get; set; }
    }
}
