//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadBuyerManager
    {
        public string EmpNo { get; set; }
        public string EmployeeName { get; set; }
        public string Role { get; set; }
        public int RoleOrder { get; set; }
        public int Itemdetailsid { get; set; }
        public bool BoolValidRevision { get; set; }
    }
}
