//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoadItemsByID
    {
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string OldVendorCode { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Blocked { get; set; }
        public string Emailid { get; set; }
        public string ContactNo { get; set; }
        public string PaymentTermCode { get; set; }
        public string RFQNo { get; set; }
        public Nullable<int> MPRRevisionId { get; set; }
        public int RfqMasterId { get; set; }
        public int VendorId { get; set; }
        public bool DeleteFlag { get; set; }
        public int rfqRevisionId { get; set; }
        public int RevisionNo { get; set; }
        public System.DateTime RFQValidDate { get; set; }
        public string PackingForwarding { get; set; }
        public string ExciseDuty { get; set; }
        public string SalesTax { get; set; }
        public string Freight { get; set; }
        public string CustomsDuty { get; set; }
        public Nullable<int> ShipmentModeid { get; set; }
        public string Insurance { get; set; }
        public Nullable<int> PaymentTermDays { get; set; }
        public string PaymentTermRemarks { get; set; }
        public string BankGuarantee { get; set; }
        public Nullable<int> DeliveryMinWeeks { get; set; }
        public Nullable<int> DeliveryMaxWeeks { get; set; }
        public int RFQItemsId { get; set; }
        public Nullable<int> MPRItemDetailsid { get; set; }
        public double QuotationQty { get; set; }
        public string VendorModelNo { get; set; }
        public Nullable<byte> DepartmentId { get; set; }
        public string JobName { get; set; }
        public string JobCode { get; set; }
        public string HSNCode { get; set; }
        public bool ItemDeleteFlag { get; set; }
        public double vendorQuoteQty { get; set; }
        public int UOM { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal DiscountPercentage { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> TargetSpend { get; set; }
        public string Department { get; set; }
        public decimal Discount { get; set; }
        public int CurrencyId { get; set; }
        public decimal CurrencyValue { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public bool Expr1 { get; set; }
        public string Materialdescription { get; set; }
        public string Material { get; set; }
        public byte BuyerGroupId { get; set; }
        public string BuyerGroup { get; set; }
        public string DocumentNo { get; set; }
        public string SaleOrderNo { get; set; }
        public string ProjectManager { get; set; }
        public Nullable<int> paid { get; set; }
        public string Status { get; set; }
        public string itemstatus { get; set; }
    }
}
