//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialMasterYG
    {
        public string Material { get; set; }
        public string MaterialType { get; set; }
        public string Materialdescription { get; set; }
        public string MaterialGroup { get; set; }
        public string UOM { get; set; }
        public string Producthierarchy { get; set; }
        public string Materialisconfigurable { get; set; }
        public string AuthorizationGroup { get; set; }
        public string ExtMaterialGroup { get; set; }
        public string Genitemcatgrp { get; set; }
        public string Securityexportcontrolitem { get; set; }
        public string Plant { get; set; }
        public string PurchasingGroup { get; set; }
        public string MRPType { get; set; }
        public string MRPController { get; set; }
        public string Lotsize { get; set; }
        public string Procurementtype { get; set; }
        public string AutomaticPO { get; set; }
        public string Sourcelist { get; set; }
        public string Serialnoprofile { get; set; }
        public string StoragelocforEP { get; set; }
        public string CASnumber { get; set; }
        public string Controlcode { get; set; }
    }
}
