//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPR_Assignment
    {
        public int assignmentid { get; set; }
        public int MprRevisionId { get; set; }
        public string Employeeno { get; set; }
        public bool deleteFlag { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual MPRRevision MPRRevision { get; set; }
    }
}
