//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRApprover
    {
        public string EmployeeNo { get; set; }
        public bool BoolActive { get; set; }
        public string DeactivatedBy { get; set; }
        public Nullable<System.DateTime> DeactivatedOn { get; set; }
    
        public virtual MPRApprover MPRApprovers1 { get; set; }
        public virtual MPRApprover MPRApprover1 { get; set; }
    }
}
