//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRDepartmentsView
    {
        public byte DepartmentId { get; set; }
        public string Department { get; set; }
        public string SecondApprover { get; set; }
        public string ThirdApprover { get; set; }
        public bool BoolInUse { get; set; }
        public string SecondApproverName { get; set; }
        public string ThirdApproverName { get; set; }
    }
}
