//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MPRDepartment()
        {
            this.MPRPADetails = new HashSet<MPRPADetail>();
            this.MPRRevisions = new HashSet<MPRRevision>();
        }
    
        public byte DepartmentId { get; set; }
        public Nullable<short> ORgDepartmentid { get; set; }
        public string Department { get; set; }
        public string SecondApprover { get; set; }
        public string ThirdApprover { get; set; }
        public bool BoolInUse { get; set; }
    
        public virtual MPRDepartment MPRDepartments1 { get; set; }
        public virtual MPRDepartment MPRDepartment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRPADetail> MPRPADetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRRevision> MPRRevisions { get; set; }
    }
}
