//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRItemInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MPRItemInfo()
        {
            this.MPRDocuments = new HashSet<MPRDocument>();
            this.PAItems = new HashSet<PAItem>();
            this.MPRRfqItems = new HashSet<MPRRfqItem>();
            this.RFQItems = new HashSet<RFQItem>();
            this.RFQMPRMappings = new HashSet<RFQMPRMapping>();
        }
    
        public int Itemdetailsid { get; set; }
        public Nullable<int> RevisionId { get; set; }
        public string Itemid { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<byte> UnitId { get; set; }
        public string SaleOrderNo { get; set; }
        public string SOLineItemNo { get; set; }
        public Nullable<decimal> TargetSpend { get; set; }
        public string ReferenceDocNo { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public string MfgPartNo { get; set; }
        public string MfgModelNo { get; set; }
        public Nullable<int> PAid { get; set; }
        public Nullable<int> RepeatOrderRefId { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<decimal> POPrice { get; set; }
        public string PORemarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRDocument> MPRDocuments { get; set; }
        public virtual MPRPADetail MPRPADetail { get; set; }
        public virtual MPRRevision MPRRevision { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAItem> PAItems { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRRfqItem> MPRRfqItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQItem> RFQItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQMPRMapping> RFQMPRMappings { get; set; }
    }
}
