//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRRevisionDetails_woItems
    {
        public int RevisionId { get; set; }
        public int RequisitionId { get; set; }
        public string DocumentNo { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<byte> DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string ProjectManagerName { get; set; }
        public string ProjectManager { get; set; }
        public string JobName { get; set; }
        public string JobCode { get; set; }
        public string GEPSApprovalId { get; set; }
        public string SaleOrderNo { get; set; }
        public string LineItemNo { get; set; }
        public string ClientId { get; set; }
        public string ClientName { get; set; }
        public byte BuyerGroupId { get; set; }
        public string BuyerGroupName { get; set; }
        public Nullable<byte> PurchaseTypeId { get; set; }
        public Nullable<byte> PreferredVendorTypeId { get; set; }
        public decimal TargetedSpendAmount { get; set; }
        public string TargetedSpendRemarks { get; set; }
        public bool BoolPreferredVendor { get; set; }
        public string JustificationForSinglePreferredVendor { get; set; }
        public Nullable<System.DateTime> DeliveryRequiredBy { get; set; }
        public byte IssuePurposeId { get; set; }
        public string DispatchLocation { get; set; }
        public Nullable<byte> ScopeId { get; set; }
        public string Scope { get; set; }
        public string TrainingRemarks { get; set; }
        public bool BoolDocumentationApplicable { get; set; }
        public string GuaranteePeriod { get; set; }
        public byte NoOfSetsOfQAP { get; set; }
        public bool InspectionRequired { get; set; }
        public byte InspectionRequiredNew { get; set; }
        public string InspectionComments { get; set; }
        public byte TestCertificates { get; set; }
        public byte ProcurementSourceId { get; set; }
        public string CustomDuty { get; set; }
        public byte CustomsDutyId { get; set; }
        public byte ProjectDutyApplicableId { get; set; }
        public bool ExciseDutyReimbursableForBOs { get; set; }
        public bool VATReimbursableForBOs { get; set; }
        public bool ServiceTaxReimbursableForBOs { get; set; }
        public byte ExciseDutyReimbursableForBOsNew { get; set; }
        public byte SalesTaxReimbursableForBOsNew { get; set; }
        public bool SalesTaxReimbursableForBOs { get; set; }
        public byte VATReimbursableForBOsNew { get; set; }
        public string Remarks { get; set; }
        public string PreparedBy { get; set; }
        public string PreparedName { get; set; }
        public Nullable<System.DateTime> PreparedOn { get; set; }
        public string CheckedBy { get; set; }
        public string CheckedName { get; set; }
        public Nullable<System.DateTime> CheckedOn { get; set; }
        public string CheckStatus { get; set; }
        public string CheckerRemarks { get; set; }
        public string ApprovedBy { get; set; }
        public string ApproverName { get; set; }
        public Nullable<System.DateTime> ApprovedOn { get; set; }
        public string ApprovalStatus { get; set; }
        public string ApproverRemarks { get; set; }
        public string SecondApprover { get; set; }
        public string SecondApproverName { get; set; }
        public Nullable<System.DateTime> SecondApprovedOn { get; set; }
        public string SecondApproversStatus { get; set; }
        public string SecondApproverRemarks { get; set; }
        public string ThirdApprover { get; set; }
        public string ThirdApproverName { get; set; }
        public string ThirdApproverStatus { get; set; }
        public Nullable<System.DateTime> ThirdApproverStatusChangedOn { get; set; }
        public string ThirdApproverRemarks { get; set; }
        public string OCheckedBy { get; set; }
        public string OCheckedName { get; set; }
        public Nullable<System.DateTime> OCheckedOn { get; set; }
        public string OCheckStatus { get; set; }
        public string OCheckerRemarks { get; set; }
        public string OApprovedBy { get; set; }
        public string OApproverName { get; set; }
        public Nullable<System.DateTime> OApprovedOn { get; set; }
        public string OApprovalStatus { get; set; }
        public string OApproverRemarks { get; set; }
        public string OSecondApprover { get; set; }
        public string OSecondApproverName { get; set; }
        public Nullable<System.DateTime> OSecondApprovedOn { get; set; }
        public string OSecondApproversStatus { get; set; }
        public string OSecondApproverRemarks { get; set; }
        public string OThirdApprover { get; set; }
        public string OThirdApproverName { get; set; }
        public string OThirdApproverStatus { get; set; }
        public Nullable<System.DateTime> OThirdApproverStatusChangedOn { get; set; }
        public string OThirdApproverRemarks { get; set; }
        public string PurchaseDetailsReadBy { get; set; }
        public Nullable<System.DateTime> PurchaseDetailsReadOn { get; set; }
        public string PurchasePersonnel { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<System.DateTime> ExpectedDespatchDate { get; set; }
        public string PurchasePersonnelsComments { get; set; }
        public Nullable<System.DateTime> TechDocsReceivedDate { get; set; }
        public Nullable<System.DateTime> CommercialOfferReceivedDate { get; set; }
        public string OfferDetailsMailedBy { get; set; }
        public Nullable<System.DateTime> OfferDetailsMailedOn { get; set; }
        public Nullable<System.DateTime> OfferDetailsViewedByCheckerOn { get; set; }
        public Nullable<System.DateTime> OfferDetailsViewedByApproverOn { get; set; }
        public Nullable<System.DateTime> MaterialReceiptDate { get; set; }
        public decimal EstimatedCost { get; set; }
        public decimal PreviousPOPrice { get; set; }
        public byte StatusId { get; set; }
        public decimal PurchaseCost { get; set; }
        public byte RevisionNo { get; set; }
        public bool BoolValidRevision { get; set; }
        public string PurchaseType { get; set; }
        public string PreferredVendorType { get; set; }
        public string ProcurementSource { get; set; }
        public string ProjectDutyApplicable { get; set; }
        public string PlantLocation { get; set; }
        public Nullable<byte> MPRStatusId { get; set; }
        public string MPRStatus { get; set; }
    }
}
