//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRRfqItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MPRRfqItem()
        {
            this.MPRRfqItemInfos = new HashSet<MPRRfqItemInfo>();
        }
    
        public int MPRRFQitemId { get; set; }
        public Nullable<int> MPRRevisionId { get; set; }
        public Nullable<int> MPRItemDetailsid { get; set; }
        public Nullable<int> RfqItemsid { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual MPRItemInfo MPRItemInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRRfqItemInfo> MPRRfqItemInfos { get; set; }
        public virtual RFQItems_N RFQItems_N { get; set; }
    }
}
