//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRRfqItemInfo
    {
        public int Mprrfqsplititemid { get; set; }
        public Nullable<int> MPRRFQitemId { get; set; }
        public Nullable<int> rfqsplititemid { get; set; }
        public Nullable<bool> Deleteflag { get; set; }
        public Nullable<int> PAItemID { get; set; }
    
        public virtual MPRRfqItemInfo MPRRfqItemInfos1 { get; set; }
        public virtual MPRRfqItemInfo MPRRfqItemInfo1 { get; set; }
        public virtual MPRRfqItem MPRRfqItem { get; set; }
        public virtual PAItem PAItem { get; set; }
        public virtual RFQItemsInfo_N RFQItemsInfo_N { get; set; }
    }
}
