//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MPRStatusTrackDetail
    {
        public byte StatusId { get; set; }
        public string Status { get; set; }
        public int RequisitionId { get; set; }
        public int RevisionId { get; set; }
        public int StatusTrackId { get; set; }
        public string Remarks { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Name { get; set; }
        public string EmployeeNo { get; set; }
    }
}
