//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgDepartment
    {
        public short OrgDepartmentId { get; set; }
        public string OrgDepartment1 { get; set; }
        public string DepartmentHead { get; set; }
        public bool BoolInUse { get; set; }
    }
}
