//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAandCRMapping
    {
        public string EmployeeNo { get; set; }
        public string Name { get; set; }
        public string role { get; set; }
        public string AuthorizationType { get; set; }
        public byte DepartmentId { get; set; }
        public decimal minpavalue { get; set; }
        public decimal maxpavalue { get; set; }
        public int MaxDays { get; set; }
        public int MinDays { get; set; }
        public Nullable<bool> lessbudget { get; set; }
        public Nullable<bool> morebudget { get; set; }
        public string FunctionalRoleId { get; set; }
        public Nullable<byte> roleorder { get; set; }
    }
}
