//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAAuthorizationEmployeeMapping
    {
        public int PAmapid { get; set; }
        public int Authid { get; set; }
        public string Employeeid { get; set; }
        public bool LessBudget { get; set; }
        public bool MoreBudget { get; set; }
        public string FunctionalRoleId { get; set; }
        public bool DeleteFlag { get; set; }
        public string CreatedBY { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual PAAuthorizationLimit PAAuthorizationLimit { get; set; }
        public virtual PAFunctionalRole PAFunctionalRole { get; set; }
    }
}
