//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAAuthorizationLimit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAAuthorizationLimit()
        {
            this.PAAuthorizationEmployeeMappings = new HashSet<PAAuthorizationEmployeeMapping>();
        }
    
        public int Authid { get; set; }
        public int DeptId { get; set; }
        public decimal MinPAValue { get; set; }
        public decimal MaxPAValue { get; set; }
        public string AuthorizationType { get; set; }
        public bool DeleteFlag { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DeletedBY { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAAuthorizationEmployeeMapping> PAAuthorizationEmployeeMappings { get; set; }
    }
}
