//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACreditDaysApprover
    {
        public int CRApprovalId { get; set; }
        public int AuthId { get; set; }
        public string EmployeeNo { get; set; }
        public byte CreditdaysId { get; set; }
        public string Createdby { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool DeleteFlag { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string FunctionalRoleId { get; set; }
    
        public virtual PACreditDaysMaster PACreditDaysMaster { get; set; }
        public virtual PAFunctionalRole PAFunctionalRole { get; set; }
    }
}
