//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAFunctionalRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAFunctionalRole()
        {
            this.PAAuthorizationEmployeeMappings = new HashSet<PAAuthorizationEmployeeMapping>();
            this.PACreditDaysApprovers = new HashSet<PACreditDaysApprover>();
        }
    
        public string FunctionalRoleId { get; set; }
        public Nullable<byte> DepartmentID { get; set; }
        public string FunctionalRole { get; set; }
        public Nullable<byte> XOrder { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAAuthorizationEmployeeMapping> PAAuthorizationEmployeeMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PACreditDaysApprover> PACreditDaysApprovers { get; set; }
    }
}
