//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PAItem()
        {
            this.MPRRfqItemInfos = new HashSet<MPRRfqItemInfo>();
        }
    
        public int PAItemID { get; set; }
        public int PAID { get; set; }
        public int RfqSplitItemId { get; set; }
        public string PONO { get; set; }
        public string POItemNo { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> MPRItemDetailsId { get; set; }
    
        public virtual MPRItemInfo MPRItemInfo { get; set; }
        public virtual MPRPADetail MPRPADetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRRfqItemInfo> MPRRfqItemInfos { get; set; }
    }
}
