//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PATerm
    {
        public int PATermID { get; set; }
        public int PAID { get; set; }
        public int RfqTermId { get; set; }
    
        public virtual MPRPADetail MPRPADetail { get; set; }
        public virtual RFQTerm RFQTerm { get; set; }
    }
}
