//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateContract
    {
        public string RFQNo { get; set; }
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string PaymentTermCode { get; set; }
        public Nullable<bool> VendorVisibility { get; set; }
        public string RFQType { get; set; }
        public Nullable<double> QuotationQty { get; set; }
        public string HSNCode { get; set; }
        public decimal UnitPrice { get; set; }
        public double vendorQuoteQty { get; set; }
        public decimal Discount { get; set; }
        public Nullable<System.DateTime> QuoteValidfrom { get; set; }
        public Nullable<System.DateTime> QuoteValidTo { get; set; }
        public int RFQItemsId { get; set; }
        public string ItemId { get; set; }
        public int RFQSplitItemId { get; set; }
        public Nullable<double> StartQty { get; set; }
        public Nullable<double> EndQty { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string Status { get; set; }
    }
}
