//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepeatOrdersView
    {
        public string RFQType { get; set; }
        public Nullable<int> MPRRevisionId { get; set; }
        public int MPRItemDetailsid { get; set; }
        public string ItemId { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<decimal> TargetSpend { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<byte> UnitId { get; set; }
        public string Materialdescription { get; set; }
        public Nullable<int> RfqSplitItemId { get; set; }
        public Nullable<int> RFQItemId { get; set; }
        public Nullable<double> QuotationQty { get; set; }
        public string RFQNo { get; set; }
        public string PaymentTermCode { get; set; }
        public Nullable<double> vendorQuoteQty { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string HsNCode { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> PAItemID { get; set; }
        public string PONO { get; set; }
    }
}
