//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFQItem()
        {
            this.RFQCommunications = new HashSet<RFQCommunication>();
        }
    
        public int RFQItemsId { get; set; }
        public int RFQRevisionId { get; set; }
        public int? MPRItemDetailsid { get; set; }
        public double QuotationQty { get; set; }
        public string VendorModelNo { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> CustomDuty { get; set; }
        public Nullable<decimal> FreightPercentage { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> PFPercentage { get; set; }
        public Nullable<decimal> PFAmount { get; set; }
        public Nullable<decimal> IGSTPercentage { get; set; }
        public Nullable<decimal> CGSTPercentage { get; set; }
        public Nullable<decimal> SGSTPercentage { get; set; }
        public Nullable<bool> taxInclusiveOfDiscount { get; set; }
        public string RequestRemarks { get; set; }
        public bool DeleteFlag { get; set; }
        public string Status { get; set; }
        public string StatusUpdatedBy { get; set; }
        public Nullable<System.DateTime> StatusUpdateddate { get; set; }
        public Nullable<int> paid { get; set; }
        public string MfgPartNo { get; set; }
        public string MfgModelNo { get; set; }
    
        public virtual MPRItemInfo MPRItemInfo { get; set; }
        public virtual MPRPADetail MPRPADetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQCommunication> RFQCommunications { get; set; }
        public virtual RFQRevision RFQRevision { get; set; }
    }
}
