//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQItemsView
    {
        public int MPRRevisionId { get; set; }
        public int Itemdetailsid { get; set; }
        public string ItemDescription { get; set; }
        public string Itemid { get; set; }
        public string Materialdescription { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<byte> UnitId { get; set; }
        public bool BoolValidRevision { get; set; }
        public int Vendorid { get; set; }
        public string VendorName { get; set; }
        public string VendorCode { get; set; }
        public double rfqQty { get; set; }
        public int rfqUOM { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Discount { get; set; }
        public decimal DiscountPercentage { get; set; }
        public string Status { get; set; }
        public string RFQNo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> RFQValidDate { get; set; }
    }
}
