//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQItemsInfo_N
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFQItemsInfo_N()
        {
            this.MPRRfqItemInfos = new HashSet<MPRRfqItemInfo>();
        }
    
        public int RFQSplitItemId { get; set; }
        public int RFQItemsId { get; set; }
        public Nullable<double> StartQty { get; set; }
        public Nullable<double> EndQty { get; set; }
        public double Qty { get; set; }
        public int UOM { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal DiscountPercentage { get; set; }
        public decimal Discount { get; set; }
        public int CurrencyId { get; set; }
        public decimal CurrencyValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DeliveryDays { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string Status { get; set; }
        public string StatusUpdatedBy { get; set; }
        public Nullable<System.DateTime> StatusUpdateddate { get; set; }
        public bool DeleteFlag { get; set; }
        public Nullable<int> Paid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MPRRfqItemInfo> MPRRfqItemInfos { get; set; }
        public virtual RFQItems_N RFQItems_N { get; set; }
    }
}
