//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQListView
    {
        public int rfqRevisionId { get; set; }
        public int RevisionNo { get; set; }
        public string RFQNo { get; set; }
        public int RfqMasterId { get; set; }
        public Nullable<System.DateTime> QuoteValidfrom { get; set; }
        public Nullable<System.DateTime> QuoteValidTo { get; set; }
        public string RFQType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime RFQValidDate { get; set; }
        public Nullable<int> RequisitionId { get; set; }
        public Nullable<int> RevisionId { get; set; }
        public string DocumentNo { get; set; }
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string BuyerGroup { get; set; }
        public Nullable<byte> BuyerGroupId { get; set; }
    }
}
