//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQMPRMapping
    {
        public int RFQMPRMappingId { get; set; }
        public int RfqItemid { get; set; }
        public Nullable<int> RFQSplitItemId { get; set; }
        public int MPRItemDetailsId { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual MPRItemInfo MPRItemInfo { get; set; }
        public virtual RFQItems_N RFQItems_N { get; set; }
    }
}
