//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQQuoteView14022020
    {
        public string VendorCode { get; set; }
        public string VendorName { get; set; }
        public string OldVendorCode { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string RegionCode { get; set; }
        public string Blocked { get; set; }
        public string Emailid { get; set; }
        public string ContactNo { get; set; }
        public string PaymentTermCode { get; set; }
        public string RFQNo { get; set; }
        public Nullable<int> MPRRevisionId { get; set; }
        public int RfqMasterId { get; set; }
        public int VendorId { get; set; }
        public bool DeleteFlag { get; set; }
        public int rfqRevisionId { get; set; }
        public int RevisionNo { get; set; }
        public System.DateTime RFQValidDate { get; set; }
        public string PackingForwarding { get; set; }
        public string ExciseDuty { get; set; }
        public string SalesTax { get; set; }
        public string Freight { get; set; }
        public string CustomsDuty { get; set; }
        public Nullable<int> ShipmentModeid { get; set; }
        public string Insurance { get; set; }
        public Nullable<int> PaymentTermDays { get; set; }
        public string PaymentTermRemarks { get; set; }
        public string BankGuarantee { get; set; }
        public Nullable<int> DeliveryMinWeeks { get; set; }
        public Nullable<int> DeliveryMaxWeeks { get; set; }
        public bool ActiveRevision { get; set; }
        public int RFQItemsId { get; set; }
        public Nullable<int> MPRItemDetailsid { get; set; }
        public Nullable<double> QuotationQty { get; set; }
        public string VendorModelNo { get; set; }
        public Nullable<decimal> PFAmount { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> PFPercentage { get; set; }
        public Nullable<decimal> FreightPercentage { get; set; }
        public string HSNCode { get; set; }
        public bool ItemDeleteFlag { get; set; }
        public Nullable<double> vendorQuoteQty { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> CurrencyValue { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> Expr1 { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<int> Itemdetailsid { get; set; }
        public Nullable<decimal> MPRQuotationQty { get; set; }
        public Nullable<decimal> MprQuantity { get; set; }
        public Nullable<decimal> TargetSpend { get; set; }
        public Nullable<int> RFQSplitItemId { get; set; }
        public string Status { get; set; }
        public string Itemid { get; set; }
        public string ItemName { get; set; }
        public string Material { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> QuoteValidfrom { get; set; }
        public string RFQType { get; set; }
        public Nullable<System.DateTime> QuoteValidTo { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<double> StartQty { get; set; }
        public Nullable<double> EndQty { get; set; }
        public string RFQItemId { get; set; }
    }
}
