//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQRevisions_N
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RFQRevisions_N()
        {
            this.RFQCommunications = new HashSet<RFQCommunication>();
            this.RFQItems_N = new HashSet<RFQItems_N>();
        }
    
        public int rfqRevisionId { get; set; }
        public int rfqMasterId { get; set; }
        public int RevisionNo { get; set; }
        public string RFQType { get; set; }
        public Nullable<System.DateTime> QuoteValidfrom { get; set; }
        public Nullable<System.DateTime> QuoteValidTo { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime RFQValidDate { get; set; }
        public string PackingForwarding { get; set; }
        public string ExciseDuty { get; set; }
        public string SalesTax { get; set; }
        public string Freight { get; set; }
        public string Insurance { get; set; }
        public string CustomsDuty { get; set; }
        public Nullable<int> ShipmentModeid { get; set; }
        public Nullable<int> PaymentTermDays { get; set; }
        public string PaymentTermRemarks { get; set; }
        public string BankGuarantee { get; set; }
        public Nullable<int> DeliveryMinWeeks { get; set; }
        public Nullable<int> DeliveryMaxWeeks { get; set; }
        public string BuyergroupEmail { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public bool ActiveRevision { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQCommunication> RFQCommunications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RFQItems_N> RFQItems_N { get; set; }
        public virtual RFQMaster RFQMaster { get; set; }
    }
}
