//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RFQView140202020
    {
        public string RFQNo { get; set; }
        public int VendorId { get; set; }
        public string VendorName { get; set; }
        public string VendorCode { get; set; }
        public int RevisionNo { get; set; }
        public string RFQType { get; set; }
        public Nullable<System.DateTime> QuoteValidfrom { get; set; }
        public Nullable<System.DateTime> QuoteValidTo { get; set; }
        public System.DateTime RFQValidDate { get; set; }
        public bool ActiveRevision { get; set; }
        public Nullable<int> MPRItemDetailsid { get; set; }
        public string ItemId { get; set; }
        public Nullable<double> QuotationQty { get; set; }
        public string VendorModelNo { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> FreightPercentage { get; set; }
        public Nullable<decimal> CustomDuty { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> PFPercentage { get; set; }
        public Nullable<decimal> PFAmount { get; set; }
        public Nullable<decimal> IGSTPercentage { get; set; }
        public Nullable<decimal> CGSTPercentage { get; set; }
        public Nullable<decimal> SGSTPercentage { get; set; }
        public string RequestRemarks { get; set; }
        public string MfgPartNo { get; set; }
        public string MfgModelNo { get; set; }
        public Nullable<int> RFQSplitItemId { get; set; }
        public Nullable<double> StartQty { get; set; }
        public Nullable<double> EndQty { get; set; }
        public int RFQItemsId { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> CurrencyValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DeliveryDays { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string Status { get; set; }
    }
}
