//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YSCMEntities : DbContext
    {
        public YSCMEntities()
            : base("name=YSCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessGroupMaster> AccessGroupMasters { get; set; }
        public virtual DbSet<AccessName> AccessNames { get; set; }
        public virtual DbSet<AuthorizationItem> AuthorizationItems { get; set; }
        public virtual DbSet<AutorizationGroup> AutorizationGroups { get; set; }
        public virtual DbSet<BankDetailsForVendor> BankDetailsForVendors { get; set; }
        public virtual DbSet<ClientLogin> ClientLogins { get; set; }
        public virtual DbSet<CurrencyHistory> CurrencyHistories { get; set; }
        public virtual DbSet<CurrencyMaster> CurrencyMasters { get; set; }
      //  public virtual DbSet<DocumentTypeMaster> DocumentTypeMasters { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<GlobalGroupEmployee> GlobalGroupEmployees { get; set; }
        public virtual DbSet<GlobalGroup> GlobalGroups { get; set; }
        public virtual DbSet<ItemAttributesMaster> ItemAttributesMasters { get; set; }
        public virtual DbSet<MaterialMaster> MaterialMasters { get; set; }
        public virtual DbSet<MaterialMasterYG> MaterialMasterYGS { get; set; }
        public virtual DbSet<MPR_Assignment> MPR_Assignment { get; set; }
        public virtual DbSet<MPRApprover> MPRApprovers { get; set; }
        public virtual DbSet<MPRBuyerGroupMember> MPRBuyerGroupMembers { get; set; }
        public virtual DbSet<MPRBuyerGroup> MPRBuyerGroups { get; set; }
        public virtual DbSet<MPRCommunication> MPRCommunications { get; set; }
        public virtual DbSet<MPRCustomsDuty> MPRCustomsDuties { get; set; }
        public virtual DbSet<MPRDepartment> MPRDepartments { get; set; }
        public virtual DbSet<MPRDespatchDocCategory> MPRDespatchDocCategories { get; set; }
        public virtual DbSet<MPRDetail> MPRDetails { get; set; }
        public virtual DbSet<MPRDispatchLocation> MPRDispatchLocations { get; set; }
        public virtual DbSet<MPRDocumentation> MPRDocumentations { get; set; }
        public virtual DbSet<MPRDocumentationDescription> MPRDocumentationDescriptions { get; set; }
        public virtual DbSet<MPRDocument> MPRDocuments { get; set; }
        public virtual DbSet<MPRIncharge> MPRIncharges { get; set; }
        public virtual DbSet<MPRIssuePurpos> MPRIssuePurposes { get; set; }
        public virtual DbSet<MPRItemDetails_X> MPRItemDetails_X { get; set; }
        public virtual DbSet<MPRItemDetailsAttachment> MPRItemDetailsAttachments { get; set; }
        public virtual DbSet<MPRItemInfo> MPRItemInfoes { get; set; }
        public virtual DbSet<MPROfferDetail> MPROfferDetails { get; set; }
        public virtual DbSet<MPRPAApprover> MPRPAApprovers { get; set; }
        public virtual DbSet<MPRPADetail> MPRPADetails { get; set; }
        public virtual DbSet<MPRPADocument> MPRPADocuments { get; set; }
        public virtual DbSet<MPRPAPurchaseMode> MPRPAPurchaseModes { get; set; }
        public virtual DbSet<MPRPAPurchaseType> MPRPAPurchaseTypes { get; set; }
        public virtual DbSet<MPRPAVendor> MPRPAVendors { get; set; }
        public virtual DbSet<MPRPreferredVendorType> MPRPreferredVendorTypes { get; set; }
        public virtual DbSet<MPRProcurementSource> MPRProcurementSources { get; set; }
        public virtual DbSet<MPRProjectDutyApplicable> MPRProjectDutyApplicables { get; set; }
        public virtual DbSet<MPRPurchaseType> MPRPurchaseTypes { get; set; }
        public virtual DbSet<MPRReminderTracking> MPRReminderTrackings { get; set; }
        public virtual DbSet<MPRRevision> MPRRevisions { get; set; }
        public virtual DbSet<MPRRfqItemInfo> MPRRfqItemInfos { get; set; }
        public virtual DbSet<MPRRfqItem> MPRRfqItems { get; set; }
        public virtual DbSet<MPRScope> MPRScopes { get; set; }
        public virtual DbSet<MPRStatu> MPRStatus { get; set; }
        public virtual DbSet<MPRStatusTrack> MPRStatusTracks { get; set; }
        public virtual DbSet<MPRTargetedSpendSupportingDoc> MPRTargetedSpendSupportingDocs { get; set; }
        public virtual DbSet<MPRVendorDetail> MPRVendorDetails { get; set; }
        public virtual DbSet<NatureOfBusinessMaster> NatureOfBusinessMasters { get; set; }
        public virtual DbSet<OrgDepartment> OrgDepartments { get; set; }
        public virtual DbSet<PAAuthorizationEmployeeMapping> PAAuthorizationEmployeeMappings { get; set; }
        public virtual DbSet<PAAuthorizationLimit> PAAuthorizationLimits { get; set; }
        public virtual DbSet<PACreditDaysApprover> PACreditDaysApprovers { get; set; }
        public virtual DbSet<PACreditDaysMaster> PACreditDaysMasters { get; set; }
        public virtual DbSet<PAFunctionalRole> PAFunctionalRoles { get; set; }
        public virtual DbSet<PAItem> PAItems { get; set; }
        public virtual DbSet<PATerm> PATerms { get; set; }
        public virtual DbSet<RFQCommunication> RFQCommunications { get; set; }
        public virtual DbSet<RFQDocument> RFQDocuments { get; set; }
        public virtual DbSet<RFQItem> RFQItems { get; set; }
        public virtual DbSet<RFQItems_N> RFQItems_N { get; set; }
        public virtual DbSet<RFQItemsInfo> RFQItemsInfoes { get; set; }
        public virtual DbSet<RFQItemsInfo_N> RFQItemsInfo_N { get; set; }
        public virtual DbSet<RFQMaster> RFQMasters { get; set; }
        public virtual DbSet<RFQMPRMapping> RFQMPRMappings { get; set; }
        public virtual DbSet<RFQReminderTracking> RFQReminderTrackings { get; set; }
        public virtual DbSet<RFQRevision> RFQRevisions { get; set; }
        public virtual DbSet<RFQRevisions_N> RFQRevisions_N { get; set; }
        public virtual DbSet<RFQStatu> RFQStatus { get; set; }
        public virtual DbSet<RFQTerm> RFQTerms { get; set; }
        public virtual DbSet<RfqVendorBOM> RfqVendorBOMs { get; set; }
        public virtual DbSet<RFQVendorTerm> RFQVendorTerms { get; set; }
        public virtual DbSet<SCMStatu> SCMStatus { get; set; }
        public virtual DbSet<ShipmentModeMaster> ShipmentModeMasters { get; set; }
        public virtual DbSet<StandardListYNN> StandardListYNNs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TermsCategory> TermsCategories { get; set; }
        public virtual DbSet<Test_AttributeMaster> Test_AttributeMaster { get; set; }
        public virtual DbSet<Test_CategoryAttributes> Test_CategoryAttributes { get; set; }
        public virtual DbSet<Test_CategoryMaster> Test_CategoryMaster { get; set; }
        public virtual DbSet<Test_ItemAttributesMaster> Test_ItemAttributesMaster { get; set; }
        public virtual DbSet<Test_ItemMaster> Test_ItemMaster { get; set; }
        public virtual DbSet<testuserdetail> testuserdetails { get; set; }
        public virtual DbSet<UnitMaster> UnitMasters { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<VendorMaster> VendorMasters { get; set; }
        public virtual DbSet<VendorRegisterDocumenetMaster> VendorRegisterDocumenetMasters { get; set; }
        public virtual DbSet<VendorRegisterDocumentDetail> VendorRegisterDocumentDetails { get; set; }
        public virtual DbSet<VendorRegisterMaster> VendorRegisterMasters { get; set; }
        public virtual DbSet<VendorRFQTerm> VendorRFQTerms { get; set; }
        public virtual DbSet<VendorUserMaster> VendorUserMasters { get; set; }
        public virtual DbSet<YILTermsandCondition> YILTermsandConditions { get; set; }
        public virtual DbSet<YILTermsGroup> YILTermsGroups { get; set; }
        public virtual DbSet<CustomerMasterYG> CustomerMasterYGS { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<MPRTechClearance> MPRTechClearances { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<AccessRoleView> AccessRoleViews { get; set; }
        public virtual DbSet<approverFinalview> approverFinalviews { get; set; }
        public virtual DbSet<CreditApprover> CreditApprovers { get; set; }
        public virtual DbSet<DisplayRfqTermsByRevisionId> DisplayRfqTermsByRevisionIds { get; set; }
        public virtual DbSet<Employeemappingtocredit> Employeemappingtocredits { get; set; }
        public virtual DbSet<Employeemappingtopurchase> Employeemappingtopurchases { get; set; }
        public virtual DbSet<GetMappedSlab> GetMappedSlabs { get; set; }
        public virtual DbSet<GetmprApproverdeatil> GetmprApproverdeatils { get; set; }
        public virtual DbSet<GetMprPaDetailsByFilter> GetMprPaDetailsByFilters { get; set; }
        public virtual DbSet<getrevision> getrevisions { get; set; }
        public virtual DbSet<getrevision1> getrevisions1 { get; set; }
        public virtual DbSet<LoadApproverEmployee> LoadApproverEmployees { get; set; }
        public virtual DbSet<LoadBuyerManager> LoadBuyerManagers { get; set; }
        public virtual DbSet<LoadItemsByID> LoadItemsByIDs { get; set; }
        public virtual DbSet<LoadItemsByPAID> LoadItemsByPAIDs { get; set; }
        public virtual DbSet<LoadProjectManager> LoadProjectManagers { get; set; }
        public virtual DbSet<MPR_GetAssignEmployee> MPR_GetAssignEmployee { get; set; }
        public virtual DbSet<MPR_GetAssignEmployeList> MPR_GetAssignEmployeList { get; set; }
        public virtual DbSet<MPRApproversView> MPRApproversViews { get; set; }
        public virtual DbSet<MPRDepartmentsView> MPRDepartmentsViews { get; set; }
        public virtual DbSet<MPRRevisionDetail> MPRRevisionDetails { get; set; }
        public virtual DbSet<MPRRevisionDetails_woItems> MPRRevisionDetails_woItems { get; set; }
        public virtual DbSet<MPRStatusTrackDetail> MPRStatusTrackDetails { get; set; }
        public virtual DbSet<PAandCRMapping> PAandCRMappings { get; set; }
        public virtual DbSet<RateContract> RateContracts { get; set; }
        public virtual DbSet<RepeatOrdersView> RepeatOrdersViews { get; set; }
        public virtual DbSet<RFQCompareView> RFQCompareViews { get; set; }
        public virtual DbSet<RFQCompareView_BK17_02_2020> RFQCompareView_BK17_02_2020 { get; set; }
        public virtual DbSet<RFQItemsView> RFQItemsViews { get; set; }
        public virtual DbSet<RFQListView> RFQListViews { get; set; }
        public virtual DbSet<RFQQuoteView> RFQQuoteViews { get; set; }
        public virtual DbSet<RFQQuoteView1> RFQQuoteView1 { get; set; }
        public virtual DbSet<RFQQuoteView14022020> RFQQuoteView14022020 { get; set; }
        public virtual DbSet<RFQView140202020> RFQView140202020 { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<VendorEmployeeView> VendorEmployeeViews { get; set; }
    }
}
