//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipmentModeMaster
    {
        public int ShipmentModeid { get; set; }
        public string Mode { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime updatedDate { get; set; }
        public bool DeleteFlag { get; set; }
        public string DeletedBY { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
