//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermission
    {
        public int RoleId { get; set; }
        public string RoleName { get; set; }
        public string UpdatedBy { get; set; }
        public int AccessNameID { get; set; }
        public string AccessName { get; set; }
        public int RoleAccessNameid { get; set; }
    }
}
