//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorUserMaster
    {
        public string Vuserid { get; set; }
        public int VendorId { get; set; }
        public string pwd { get; set; }
        public bool Active { get; set; }
        public bool SuperUser { get; set; }
        public string VuniqueId { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string ContactPerson { get; set; }
        public string ContactNumber { get; set; }
    }
}
