//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class VendorRegisterDocumenetMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VendorRegisterDocumenetMaster()
        {
            this.VendorRegisterDocumentDetails = new HashSet<VendorRegisterDocumentDetail>();
        }
    
        public int DocumentationTypeId { get; set; }
        public string Documentype { get; set; }
        public Nullable<bool> IsNewRegister { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorRegisterDocumentDetail> VendorRegisterDocumentDetails { get; set; }
    }
}
