//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.SCMModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class YILTermsandCondition
    {
        public int TermId { get; set; }
        public byte TermGroupId { get; set; }
        public Nullable<int> BuyerGroupId { get; set; }
        public string Terms { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public bool DefaultSelect { get; set; }
        public string DeleteFlag { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    }
}
