//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteForgetPassword
    {
        public string emailId { get; set; }
        public string ResetURL { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> ExpirtyDateAndTime { get; set; }
        public Nullable<System.DateTime> URLGeneratedOn { get; set; }
        public Nullable<bool> TokenUsed { get; set; }
    }
}
