//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteVendorRegisterDocumentDetail
    {
        public int Id { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string PhysicalPath { get; set; }
        public Nullable<System.DateTime> UploadedOn { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> DocumentationTypeId { get; set; }
    
        public virtual RemoteVendorRegisterDocumenetMaster RemoteVendorRegisterDocumenetMaster { get; set; }
        public virtual RemoteVendorRegisterMaster RemoteVendorRegisterMaster { get; set; }
    }
}
