//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VSCMEntities : DbContext
    {
        public VSCMEntities()
            : base("name=VSCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RemoteBankDetailsForVendor> RemoteBankDetailsForVendors { get; set; }
        public virtual DbSet<RemoteCurrencyHistory> RemoteCurrencyHistories { get; set; }
        public virtual DbSet<RemoteCurrencyMaster> RemoteCurrencyMasters { get; set; }
        public virtual DbSet<RemoteDocumentTypeMaster> RemoteDocumentTypeMasters { get; set; }
        public virtual DbSet<RemoteForgetPassword> RemoteForgetPasswords { get; set; }
        public virtual DbSet<RemoteNatureOfBusinessMaster> RemoteNatureOfBusinessMasters { get; set; }
        public virtual DbSet<RemoteRFQCommunication> RemoteRFQCommunications { get; set; }
        public virtual DbSet<RemoteRFQDocument> RemoteRFQDocuments { get; set; }
        public virtual DbSet<RemoteRFQItem> RemoteRFQItems { get; set; }
        public virtual DbSet<RemoteRFQItems_N> RemoteRFQItems_N { get; set; }
        public virtual DbSet<RemoteRFQItemsInfo> RemoteRFQItemsInfoes { get; set; }
        public virtual DbSet<RemoteRFQItemsInfo_N> RemoteRFQItemsInfo_N { get; set; }
        public virtual DbSet<RemoteRFQMaster> RemoteRFQMasters { get; set; }
        public virtual DbSet<RemoteRFQMPRMapping> RemoteRFQMPRMappings { get; set; }
        public virtual DbSet<RemoteRFQReminderTracking> RemoteRFQReminderTrackings { get; set; }
        public virtual DbSet<RemoteRFQRevision> RemoteRFQRevisions { get; set; }
        public virtual DbSet<RemoteRFQRevisions_N> RemoteRFQRevisions_N { get; set; }
        public virtual DbSet<RemoteRFQStatu> RemoteRFQStatus { get; set; }
        public virtual DbSet<RemoteRFQStatusUpdate> RemoteRFQStatusUpdates { get; set; }
        public virtual DbSet<RemoteRfqTerm> RemoteRfqTerms { get; set; }
        public virtual DbSet<RemoteRfqVendorBOM> RemoteRfqVendorBOMs { get; set; }
        public virtual DbSet<RemoteRFQVendorTerm> RemoteRFQVendorTerms { get; set; }
        public virtual DbSet<RemoteShipmentModeMaster> RemoteShipmentModeMasters { get; set; }
        public virtual DbSet<RemoteStateMaster> RemoteStateMasters { get; set; }
        public virtual DbSet<RemoteUnitMaster> RemoteUnitMasters { get; set; }
        public virtual DbSet<RemoteVendorMaster> RemoteVendorMasters { get; set; }
        public virtual DbSet<RemoteVendorRegisterDocumenetMaster> RemoteVendorRegisterDocumenetMasters { get; set; }
        public virtual DbSet<RemoteVendorRegisterDocumentDetail> RemoteVendorRegisterDocumentDetails { get; set; }
        public virtual DbSet<RemoteVendorRegisterMaster> RemoteVendorRegisterMasters { get; set; }
        public virtual DbSet<RemoteVendorRFQTerm> RemoteVendorRFQTerms { get; set; }
        public virtual DbSet<RemoteVendorUserMaster> RemoteVendorUserMasters { get; set; }
        public virtual DbSet<RFQPendingQuotation> RFQPendingQuotations { get; set; }
        public virtual DbSet<V_RFQList> V_RFQList { get; set; }
    }
}
