//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteRfqVendorBOM
    {
        public int RFQVendorbomItemId { get; set; }
        public int RfqItemsId { get; set; }
        public Nullable<int> MPRItemDetailsid { get; set; }
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public Nullable<double> QuotationQty { get; set; }
        public string VendorModelNo { get; set; }
        public string MfgPartNo { get; set; }
        public string MfgModelNo { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> CustomDuty { get; set; }
        public Nullable<decimal> FreightPercentage { get; set; }
        public Nullable<decimal> FreightAmount { get; set; }
        public Nullable<decimal> PFPercentage { get; set; }
        public Nullable<decimal> PFAmount { get; set; }
        public Nullable<decimal> IGSTPercentage { get; set; }
        public Nullable<decimal> CGSTPercentage { get; set; }
        public Nullable<decimal> SGSTPercentage { get; set; }
        public Nullable<bool> taxInclusiveOfDiscount { get; set; }
        public string RequestRemarks { get; set; }
        public Nullable<double> Qty { get; set; }
        public Nullable<int> UOM { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> CurrencyValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DeliveryDays { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    
        public virtual RemoteRFQItems_N RemoteRFQItems_N { get; set; }
    }
}
