//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteRfqTerm
    {
        public int VRfqTermsid { get; set; }
        public int RfqRevisionId { get; set; }
        public int termsid { get; set; }
        public string TermGroup { get; set; }
        public string Terms { get; set; }
        public string VendorResponse { get; set; }
        public string Remarks { get; set; }
        public bool DeleteFlag { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool SyncStatus { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
