//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteUnitMaster
    {
        public byte UnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
    }
}
