//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteVendorRegisterMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RemoteVendorRegisterMaster()
        {
            this.RemoteBankDetailsForVendors = new HashSet<RemoteBankDetailsForVendor>();
            this.RemoteVendorRegisterDocumentDetails = new HashSet<RemoteVendorRegisterDocumentDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<bool> Onetimevendor { get; set; }
        public Nullable<bool> EvaluationRequired { get; set; }
        public string VendorNoInSAP { get; set; }
        public Nullable<System.DateTime> RequestedOn { get; set; }
        public string VendorName { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string LocalBranchOffice { get; set; }
        public string PhoneAndExtn { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string GSTNo { get; set; }
        public Nullable<int> NatureofBusiness { get; set; }
        public string PANNo { get; set; }
        public string CINNo { get; set; }
        public string TanNo { get; set; }
        public string PaymentTerms { get; set; }
        public Nullable<int> Vendorid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoteBankDetailsForVendor> RemoteBankDetailsForVendors { get; set; }
        public virtual RemoteNatureOfBusinessMaster RemoteNatureOfBusinessMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RemoteVendorRegisterDocumentDetail> RemoteVendorRegisterDocumentDetails { get; set; }
    }
}
