//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteRFQMPRMapping
    {
        public int RFQMPRMappingId { get; set; }
        public int RfqItemid { get; set; }
        public int MPRItemDetailsId { get; set; }
        public Nullable<int> RFQSplitItemId { get; set; }
        public bool DeleteFlag { get; set; }
    
        public virtual RemoteRFQItems_N RemoteRFQItems_N { get; set; }
        public virtual RemoteRFQMPRMapping RemoteRFQMPRMapping1 { get; set; }
        public virtual RemoteRFQMPRMapping RemoteRFQMPRMapping2 { get; set; }
    }
}
