//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteCurrencyHistory
    {
        public int CurrencyHistoryId { get; set; }
        public byte CurrencyId { get; set; }
        public decimal CurrencyValue { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public System.DateTime EffectiveTo { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public string editedBy { get; set; }
        public Nullable<System.DateTime> EditedDate { get; set; }
    
        public virtual RemoteCurrencyMaster RemoteCurrencyMaster { get; set; }
    }
}
