//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteRFQItemsInfo_N
    {
        public int RFQSplitItemId { get; set; }
        public int RFQItemsId { get; set; }
        public Nullable<double> StartQty { get; set; }
        public Nullable<double> EndQty { get; set; }
        public double Qty { get; set; }
        public int UOM { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal DiscountPercentage { get; set; }
        public decimal Discount { get; set; }
        public int CurrencyId { get; set; }
        public decimal CurrencyValue { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DeliveryDays { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public bool DeleteFlag { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<bool> SyncStatus { get; set; }
    
        public virtual RemoteRFQItems_N RemoteRFQItems_N { get; set; }
    }
}
