//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoteBankDetailsForVendor
    {
        public int Id { get; set; }
        public string BankDetails { get; set; }
        public string BankerName { get; set; }
        public string IFSCCode { get; set; }
        public string AccountHolderName { get; set; }
        public string LocationOrBranch { get; set; }
        public string AccNo { get; set; }
        public Nullable<int> VendorId { get; set; }
    
        public virtual RemoteVendorRegisterMaster RemoteVendorRegisterMaster { get; set; }
    }
}
