//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCMModels.RemoteModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RFQList
    {
        public string Status { get; set; }
        public Nullable<int> StatusId { get; set; }
        public int RfqMasterId { get; set; }
        public Nullable<int> MPRRevisionId { get; set; }
        public string RFQNo { get; set; }
        public Nullable<int> RFQUniqueNo { get; set; }
        public int VendorId { get; set; }
        public Nullable<bool> VendorVisiblity { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool DeleteFlag { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
        public Nullable<bool> SyncStatus { get; set; }
        public int rfqRevisionId { get; set; }
        public int RevisionNo { get; set; }
        public string RFqType { get; set; }
        public Nullable<System.DateTime> QuoteValidFrom { get; set; }
        public Nullable<System.DateTime> QuotevalidTo { get; set; }
        public int revisioncreatedBy { get; set; }
        public System.DateTime revisioncreatedDate { get; set; }
        public System.DateTime RFQValidDate { get; set; }
        public string PackingForwarding { get; set; }
        public string ExciseDuty { get; set; }
        public string SalesTax { get; set; }
        public string Freight { get; set; }
        public string Insurance { get; set; }
        public string CustomsDuty { get; set; }
        public Nullable<int> ShipmentModeid { get; set; }
        public Nullable<int> PaymentTermDays { get; set; }
        public string PaymentTermRemarks { get; set; }
        public string BankGuarantee { get; set; }
        public Nullable<int> DeliveryMinWeeks { get; set; }
        public Nullable<int> DeliveryMaxWeeks { get; set; }
        public string BuyergroupEmail { get; set; }
        public Nullable<bool> revisionDeleteflag { get; set; }
        public Nullable<bool> ActiveRevision { get; set; }
    }
}
